// src/features/chat/Chatbot.svelte
<script lang="ts">
  import Spinner from "../../layouts/spinner.svelte";
  // import { Chatbot } from "./chatbot.model";
  import {
    sendChat$,
    sendChat,
    getPrefixes$,
    getPrefixes,
  } from "./chatbot.service.js";

  let showSpinner = false;
  let chatResponse = "";
  let payload: any = {
    model: "text-davinci-003",
    prompt: "Hello world",
    temperature: 0,
    max_tokens: 200,
    prefixes: [],
  };
  let promptPrefixes = [];
  let selectedPrefixes = [0];
  let max_tokens_slider: number = 500;
  let temp_slider: number = 0.1;
  let models: any[] = [{model:"text-davinci-003", max_tokens:4096},{model:"code-davinci-002", max_tokens:8000},{model:"text-curie-001", max_tokens:2048}]
  let selectedModel: any = models[0];
  $: length = selectedPrefixes.length;
  sendChat$.subscribe((data) => {
    chatResponse = data;
    showSpinner = false;
    payload.prompt = "";
  });
  getPrefixes$.subscribe((data) => {
    promptPrefixes = data;
    showSpinner = false;
  });
  getPrefixes();

  function handleUpload() {
    showSpinner = true;
    payload.prefixes = selectedPrefixes;
    payload.model = selectedModel.model;
    payload.max_tokens = Number(max_tokens_slider);
    payload.temperature = Number(temp_slider);

    sendChat(payload);
  }

  function promptInputChange(e) {
    payload.prompt = e.target.value;
  }

  function handleMaxTokenValue(e) {
    max_tokens_slider = e.target.value;
    payload.max_tokens = Number(max_tokens_slider);
  };

  function handleTempValue(e) {
    temp_slider = e.target.value;
    payload.temperature = Number(temp_slider);
  };
  
</script>

<div class="message h-screen ">
  <slot />

  <div class="mx-auto flex flex-col">
    {#if showSpinner}
      <div class="relative top-36">
        <svelte:component this={Spinner} />
      </div>
    {/if}
    <textarea
      class="p-5 mx-auto rounded shadow-lg border-gray-800 border-2 active:border-green-500 bg-grey-100 w-full lg:w-3/4 m-5"
      rows={10}
      bind:value={chatResponse}
      readonly
    />
    <textarea
      class="p-5 mx-auto rounded shadow-lg border-gray-800 border-2 active:border-green-500 bg-grey-100 w-full lg:w-3/4 m-5"
      rows={2}
      bind:value={payload.prompt}
      on:change={promptInputChange}
    />

     <!-- multi select -->
     <div class="mx-auto w-full lg:w-3/4 rounded border-2 border-black shadow-lg">
      <select class="w-full  h-full p-3" bind:value={selectedPrefixes} >
        {#each promptPrefixes as prompt}
          <option class="flex-wrap" value={prompt.prompt}>{prompt.name}</option>
        {/each}
      </select>
    </div>
    
    <!-- This Section is for the advanced features -->
    <!-- Range Slider for token max -->
    <div class="flex flex-wrap justify-center mx-auto w-full lg:w-3/4">

      <div class=" my-3 w-full range-slider bg-white lg:w-2/6 border-2 border-black rounded shadow-lg flex">
        <input class="relative left-1 pl-5 p-3 accent-orange-500 range-slider__range w-full " type="range" value={max_tokens_slider} min="100" max={selectedModel.max_tokens} step="25" on:click={()=> handleMaxTokenValue(event)}>
        <span class=" range-slider__value p-3">{max_tokens_slider}</span>
      </div>

      <div class="mx-auto relative w-full lg:w-1/6 my-3 rounded border-2 border-black shadow-lg">
        <select class="w-full h-full p-3" bind:value={selectedModel} >
          {#each models as model}
            <option class="flex-wrap" value={model}>{model.model}</option>
          {/each}
        </select>
      </div>

      <div class="my-3 w-full range-slider bg-white lg:w-2/6 border-2 border-black rounded shadow-lg flex">
        <input class="relative left-1 pl-5 p-3 range-slider__range w-full accent-orange-500 " type="range" value={temp_slider} min="0" max="1.0" step="0.1" on:click={()=> handleTempValue(event)}>
        <span class=" range-slider__value p-3">{temp_slider}</span>
      </div>

    </div>

    <div class="flex w-full mx-auto mt-10">
      <button
        class="mx-auto w-1/4 rounded btn_w_border shadow-lg"
        on:click={handleUpload}
      >
        Send
      </button>
    </div>
  </div>
</div>

// src/features/chat/Chatbot.tsx
import React, { useState, useEffect } from "react";
import axios, { isCancel, AxiosError } from "axios";
import { OPENAI_API_KEY } from "../../env.d";
import Spinner from "../../layouts/spinner";
import { Configuration, OpenAIApi } from "openai";

export default function Chatbot() {
    const [payload, setValues] = useState({
        model: "text-davinci-003",
        prompt: "Hello world",
        temperature: 0,
        max_tokens: 200,
        // topP: 1,
        // presencePenalty: 0,
        // frequencyPenalty: 0,
        // bestOf: 1,
        // n: 1,
        // stream: false,
        // stop: ['\n', "testing"]
    });

    const [response, setChatResponse] = useState("")
    const [showSpinner, setShowSpinner] = useState(false)
    const [savedPrompts, setSavedPrompt] = useState([])

    const configuration = new Configuration({
        apiKey: OPENAI_API_KEY
    });
    const openai = new OpenAIApi(configuration);

   

    const handleUpload = async (event) => {
        setShowSpinner(true)
        try {
            const completion = await openai.createCompletion(payload);
            setChatResponse(completion.data.choices[0].text)
            console.log(completion.data.choices[0].text);
            setShowSpinner(false)
        } catch (error) {
            if (error.response) {
                console.log(error.response.status);
                console.log(error.response.data);
            } else {
                console.log(error.message);
            }
        }
    }

    const promptInputChange = (e) =>{
             setValues({
                model: payload.model,
                temperature: payload.temperature,
                max_tokens: payload.max_tokens,
                prompt: e.target.value
            })
        }
    
    

    return (
        <div className=" mx-auto flex flex-col">

            {showSpinner? (
                <div className="relative top-36">            <Spinner/>
                </div>
            ) : ("")}
            <textarea
                className="mx-auto rounded  border-gray-800 border-2 active:border-green-500 bg-grey-100 w-full lg:w-3/4 m-5"
                rows={10}
                value={response}
                readOnly
            />
            <textarea
                className="mx-auto rounded  border-gray-800 border-2 active:border-green-500 bg-grey-100 w-full lg:w-3/4 m-5"
                rows={2}
                value={payload.prompt}
                onChange={promptInputChange}
            />
            <div className="flex w-1/2 mx-auto">
                <button className="mx-auto rounded  bg-white m-4 p-4 border-gray-800 border-2" type="button"
                    onClick={handleUpload}>
                    Send
                </button>
            </div>

        </div>

    );

    }
